//! Generate the shell script that `eval` consumes.

use crate::config::package::Package;
use crate::config::paths;
use crate::config::prefs::Prefs;
use crate::inject::escape;
use anyhow::Result;
use std::collections::BTreeMap;
use std::fs;

/// What to include when generating a script.
pub struct GenOptions {
    /// Suppress human-readable comments (used for `--quiet` and SSH).
    pub quiet: bool,
    /// Include function file bodies (false for portable SSH snippets).
    pub include_functions: bool,
    /// Restrict to these packages; when `None`, use all enabled packages.
    pub only_packages: Option<Vec<String>>,
    /// SSH mode: emit ONLY entries explicitly flagged ssh-safe, and skip the
    /// local shell helpers (duh-reload/duh-cd) that assume a local duh install.
    pub ssh_safe_only: bool,
}

impl Default for GenOptions {
    fn default() -> Self {
        GenOptions {
            quiet: false,
            include_functions: true,
            only_packages: None,
            ssh_safe_only: false,
        }
    }
}

/// Build the full shell script for the given options.
pub fn generate(opts: &GenOptions) -> Result<String> {
    let prefs = Prefs::load()?;
    let packages = match &opts.only_packages {
        Some(list) => list.clone(),
        None => prefs.enabled_existing()?,
    };

    // Later packages override earlier ones; BTreeMap keeps output deterministic.
    let mut aliases: BTreeMap<String, String> = BTreeMap::new();
    let mut exports: BTreeMap<String, String> = BTreeMap::new();

    for name in &packages {
        let pkg = Package::load(name)?;
        for (k, v) in pkg.aliases {
            escape::require_valid_name("alias", &k)?;
            reject_control_chars("alias", &k, &v)?;
            // SSH mode: opt-in allowlist — skip anything not flagged ssh-safe.
            if opts.ssh_safe_only && !pkg.ssh.alias_ok(&k) {
                continue;
            }
            aliases.insert(k, v);
        }
        for (k, v) in pkg.exports {
            escape::require_valid_name("export", &k)?;
            reject_control_chars("export", &k, &v)?;
            if opts.ssh_safe_only && !pkg.ssh.export_ok(&k) {
                continue;
            }
            exports.insert(k, v);
        }
    }

    let mut out = String::new();
    if !opts.quiet {
        out.push_str("# generated by duh — do not edit; run `duh inject`\n");
    }

    for (k, v) in &exports {
        out.push_str(&format!("export {}={}\n", k, escape::single_quote(v)));
    }
    for (k, v) in &aliases {
        out.push_str(&format!("alias {}={}\n", k, escape::single_quote(v)));
    }

    if opts.include_functions {
        for name in &packages {
            for file in Package::function_files(name)? {
                let body = fs::read_to_string(&file)?;
                // Drop a leading shebang: scripts keep `#!/usr/bin/env bash` so
                // they run/edit standalone, but it's noise once sourced.
                let body = strip_shebang(&body);
                if !opts.quiet {
                    out.push_str(&format!("# function file: {}\n", file.display()));
                }
                out.push_str(body);
                if !body.ends_with('\n') {
                    out.push('\n');
                }
            }
        }
    }

    // Local-only shell helpers: a real reload (a child process can't reload the
    // parent shell, but a shell function can) and safe cd helpers.
    if !opts.ssh_safe_only {
        out.push_str(&shell_helpers(opts.quiet)?);
    }

    Ok(out)
}

/// Shell functions injected into the local shell only. These must be shell
/// functions, not `duh` subcommands: a child process can't change the parent
/// shell's cwd (`duh-cd`) or re-inject into it (`duh-reload`).
fn shell_helpers(quiet: bool) -> Result<String> {
    let packages_dir = paths::packages_dir()?;
    let mut s = String::new();
    if !quiet {
        s.push_str("# duh: shell helpers\n");
    }
    // Re-eval in the *current* shell.
    s.push_str("duh-reload() { eval \"$(duh _internal emit --quiet)\"; }\n");
    // Safe cd helper: only cd if the directory exists.
    s.push_str(&format!(
        "duh-cd() {{ [ -d {dir} ] && cd {dir} || echo 'duh: packages dir missing' >&2; }}\n",
        dir = escape::single_quote(&packages_dir.to_string_lossy())
    ));
    Ok(s)
}

/// Drop a leading shebang line (`#!…`) from a script body, if present. Only the
/// first line is considered — a shebang is meaningful only as line 1.
fn strip_shebang(body: &str) -> &str {
    if body.starts_with("#!") {
        match body.find('\n') {
            Some(nl) => &body[nl + 1..],
            None => "",
        }
    } else {
        body
    }
}

/// Reject NUL and other control characters in a value (newline excepted —
/// multi-line aliases are legitimate and stay safely single-quoted). NUL would
/// silently truncate the shell token; other control chars are never intended.
fn reject_control_chars(kind: &str, name: &str, value: &str) -> Result<()> {
    if let Some(c) = value
        .chars()
        .find(|c| c.is_control() && *c != '\n' && *c != '\t')
    {
        anyhow::bail!(
            "{kind} {name:?} contains a forbidden control character (U+{:04X})",
            c as u32
        );
    }
    Ok(())
}
