//! Generate the shell script that `eval` consumes.

use crate::config::package::Package;
use crate::config::prefs::Prefs;
use crate::inject::escape;
use anyhow::Result;
use std::collections::BTreeMap;
use std::fs;

/// What to include when generating a script.
pub struct GenOptions {
    /// Suppress human-readable comments (used for `--quiet` and SSH).
    pub quiet: bool,
    /// Include function file bodies (false for portable SSH snippets).
    pub include_functions: bool,
    /// Restrict to these packages; when `None`, use all enabled packages.
    pub only_packages: Option<Vec<String>>,
}

impl Default for GenOptions {
    fn default() -> Self {
        GenOptions {
            quiet: false,
            include_functions: true,
            only_packages: None,
        }
    }
}

/// Build the full shell script for the given options.
pub fn generate(opts: &GenOptions) -> Result<String> {
    let prefs = Prefs::load()?;
    let packages = match &opts.only_packages {
        Some(list) => list.clone(),
        None => prefs.enabled_existing()?,
    };

    // Later packages override earlier ones; BTreeMap keeps output deterministic.
    let mut aliases: BTreeMap<String, String> = BTreeMap::new();
    let mut exports: BTreeMap<String, String> = BTreeMap::new();

    for name in &packages {
        let pkg = Package::load(name)?;
        for (k, v) in pkg.aliases {
            escape::require_valid_name("alias", &k)?;
            reject_control_chars("alias", &k, &v)?;
            aliases.insert(k, v);
        }
        for (k, v) in pkg.exports {
            escape::require_valid_name("export", &k)?;
            reject_control_chars("export", &k, &v)?;
            exports.insert(k, v);
        }
    }

    let mut out = String::new();
    if !opts.quiet {
        out.push_str("# generated by duh — do not edit; run `duh inject`\n");
    }

    for (k, v) in &exports {
        out.push_str(&format!("export {}={}\n", k, escape::single_quote(v)));
    }
    for (k, v) in &aliases {
        out.push_str(&format!("alias {}={}\n", k, escape::single_quote(v)));
    }

    if opts.include_functions {
        for name in &packages {
            for file in Package::function_files(name)? {
                let body = fs::read_to_string(&file)?;
                if !opts.quiet {
                    out.push_str(&format!("# function file: {}\n", file.display()));
                }
                out.push_str(&body);
                if !body.ends_with('\n') {
                    out.push('\n');
                }
            }
        }
    }

    Ok(out)
}

/// Reject NUL and other control characters in a value (newline excepted —
/// multi-line aliases are legitimate and stay safely single-quoted). NUL would
/// silently truncate the shell token; other control chars are never intended.
fn reject_control_chars(kind: &str, name: &str, value: &str) -> Result<()> {
    if let Some(c) = value
        .chars()
        .find(|c| c.is_control() && *c != '\n' && *c != '\t')
    {
        anyhow::bail!(
            "{kind} {name:?} contains a forbidden control character (U+{:04X})",
            c as u32
        );
    }
    Ok(())
}

/// Summary counts for `duh status` (human-readable).
pub struct Counts {
    pub packages: usize,
    pub aliases: usize,
    pub exports: usize,
    pub functions: usize,
}

pub fn counts() -> Result<Counts> {
    let prefs = Prefs::load()?;
    let packages = prefs.enabled_existing()?;
    let mut aliases = 0;
    let mut exports = 0;
    let mut functions = 0;
    for name in &packages {
        let pkg = Package::load(name)?;
        aliases += pkg.aliases.len();
        exports += pkg.exports.len();
        functions += Package::function_files(name)?.len();
    }
    Ok(Counts {
        packages: packages.len(),
        aliases,
        exports,
        functions,
    })
}
